### ISSUE TITLE
add a "BugReports" field to DESCRIPTION

### ISSUE THREAD

**Issue by chrbknudsen** [KUBDatalab/KBapi#42]
nd point it to a bug tracker. Many
    online code hosting services provide bug trackers for free, https://github.com,
    https://gitlab.com, etc.

**Comment by Felipe-Rafael-Rosa** [comment]
try this

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
I put the necessary dlls in the archive
